version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Creating archive of python code.
      - echo installing ansible-container
      - git clone https://github.com/ansible/ansible-container.git
      - cd ansible-container
      - pip install -e ./ansible-container[docker]
      - cd ansible && ansible-container build --with-volumes ../:/dashboard
      - pip install docker-compose
      - cd vulnscanning/ && chmod +x start-clair.sh && ./start-clair.sh
  post_build:
    commands:
      - echo Build completed on `date`

